#file: noinspection SpellCheckingInspection
version: '3.8'

services:
  api-gateway:
    build: ./API_Gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - orchestration-service

  orchestration-service:
    build: ./Orchestration_Service
    container_name: orchestration-service
    ports:
      - "50051:50051"
    depends_on:
      - redis

  file-service:
    build: ./File_Service
    container_name: file-service
    ports:
      - "50052:50052"
    depends_on:
      - redis
      - minio
      - orchestration-service

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio-service
    command: server --console-address ":9001" --address ":9000" /data
    ports:
      - "9000:9000"
      - "9001:9001"